insert into T_EXCHANGE_VALUES ( ID ,CCY_FROM,CCY_TO,CONV_MULITPLE,PORT)  values(1, 'USD', 'INR', 70, 0);
insert into T_EXCHANGE_VALUES ( ID ,CCY_FROM,CCY_TO,CONV_MULITPLE,PORT)  values(2, 'MYR', 'INR', 17, 0);
insert into T_EXCHANGE_VALUES ( ID ,CCY_FROM,CCY_TO,CONV_MULITPLE,PORT)  values(3, 'SGD', 'INR', 53, 0);